Workflow update
1. Updated score.yml to add 2 action workflows Train & Test
2. Updated gitignore
3. Added docker file

diff --git a/.github/workflows/score.yml b/.github/workflows/score.yml
--- a/.github/workflows/score.yml
+++ b/.github/workflows/score.yml
@@ -12,27 +12,62 @@ permissions:
   contents: read
 
 jobs:
-  evaluate:
+  
+  Train:
     runs-on: ubuntu-latest
+    outputs:
+      image-tag: ${{ steps.prepare.outputs.image-tag }}
+    
     steps:
-      - uses: actions/checkout@v3
-      - name: Setup Python 3.11
-        uses: actions/setup-python@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Prepare image tag
+        id: prepare
+        run: echo "::set-output name=image-tag::$(echo ${{ github.sha }})"
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v1
         with:
-          python-version: "3.11"
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      - name: Install dependencies
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ steps.prepare.outputs.image-tag }}
+
+  Test:
+    needs: Train
+    runs-on: ubuntu-latest
+    if: ${{ needs.build-and-train.outputs.image-tag }}
+    
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+
+      - name: Pull and run Docker image
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ needs.build-and-train.outputs.image-tag }}
+          docker run --name test-container ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ needs.build-and-train.outputs.image-tag }}
 
-      - name: Create model
-        run:
-          python train.py
-
-      - name: Test model
+      - name: Check test results
         run: |
-          OUTPUT=$(python test.py)
-          echo "Score:"
-          echo "$OUTPUT"
-          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
+          result=$(docker logs test-container)
+          echo "Test results: $result"
+          if [[ "$result" != *'Score: 0.50'* ]]; then
+            echo "Test failed with score less than 0.50"
+            exit 1
+          fi
